// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPC8G3IfJlfZs8ohDipjEEiOJyGQdxtnw',
    appId: '1:894178811367:web:94b7b18df208d0df177142',
    messagingSenderId: '894178811367',
    projectId: 'jo-gest-boutique',
    authDomain: 'jo-gest-boutique.firebaseapp.com',
    storageBucket: 'jo-gest-boutique.firebasestorage.app',
    measurementId: 'G-7141LZVLTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwelXBCUlym0yb6k3V6WB7DH_yLYbmnfw',
    appId: '1:894178811367:android:9c000057ace5f8d6177142',
    messagingSenderId: '894178811367',
    projectId: 'jo-gest-boutique',
    storageBucket: 'jo-gest-boutique.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtoeX-JPTWt2tblsdVJRnvxG5YlluMmHI',
    appId: '1:894178811367:ios:ffc1331e9e29c54d177142',
    messagingSenderId: '894178811367',
    projectId: 'jo-gest-boutique',
    storageBucket: 'jo-gest-boutique.firebasestorage.app',
    iosBundleId: 'com.example.gestbouti',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtoeX-JPTWt2tblsdVJRnvxG5YlluMmHI',
    appId: '1:894178811367:ios:ffc1331e9e29c54d177142',
    messagingSenderId: '894178811367',
    projectId: 'jo-gest-boutique',
    storageBucket: 'jo-gest-boutique.firebasestorage.app',
    iosBundleId: 'com.example.gestbouti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPC8G3IfJlfZs8ohDipjEEiOJyGQdxtnw',
    appId: '1:894178811367:web:d4758480a5312542177142',
    messagingSenderId: '894178811367',
    projectId: 'jo-gest-boutique',
    authDomain: 'jo-gest-boutique.firebaseapp.com',
    storageBucket: 'jo-gest-boutique.firebasestorage.app',
    measurementId: 'G-XTWQEKT6XP',
  );
}
